### ISSUE TITLE
Websites that needs windows authentication fails to load

### ISSUE THREAD

**Issue by venkat7be1** [titanium007/Titanium#2] opened 2015-05-15 22:08 UTC
Hello, 

The websites that  needs the windows authentication over http is failing to load the pages while using the proxy.Chrome shows the message as This webpage is not available, ERR_CONTENT_LENGTH_MISMATCH. Please help me to solve the issue

**Comment by titanium007** [comment] 2015-05-15 22:26
Hi venkat,

I have successfully used chrome in my office computer to access intranet sites that uses windows authentication when proxy was running on my local machine. You may have to configure chrome. Search online for info on windows authentication on Chrome.

However, theoretically you cannot use windows authentication when proxy is running on a remote machine, because there is a double hop issue when windows uses kerberos authentication. You can get away with it by allowing delegation on the proxy server, and then modify the code to pass client credentials to server on behalf of client.   At this moment I am not working in to it, but may update in future.

**Comment by venkat7be1** [comment] 2015-05-15 23:17
Thanks For the Quick Response, The issue is not limited to Chrome but happens in IE and Firefox also. In my case there were couple of websites that were hosted on Amazon over http uses the windows authentication and failing to show Authentication popup. Please try this website which is configured for Windows Authentication. http://bestdeals9.com/

**Comment by venkat7be1** [comment] 2015-05-15 23:26
Also i have noticed few Websites that enables chat sessions is having problem with communicating. Here is one of the example i noticed that works good without proxy but errors out with proxy. 

http://makemytrip.custhelp.com/app/chat/chat_landing_chat_us/mobile/6145671627/skill/1308/ptype/http:$$us.makemytrip.com$homepage/qtype/2441/first_name/Test1/last_name/Test2/email/Test2%40gmail.com

This url errors out as " There was a problem connecting to the Chat Server" when using with Chrome and Firefox, but works good in IE8.

**Comment by venkat7be1** [comment] 2015-05-16 20:26
Another Issue is While on Post action Some sites Errors out with 417 - Expectation Failed error. this is noticed in Slickdeals.net, Not sure if its Site Specific? Any help to fix this issue is appreciated. Thanks

**Comment by titanium007** [comment] 2015-05-16 22:00
I noted the "windows authentication" issue you mentioned, though it is not windows authentication but basic authentication. I will fix it soon.

Regarding other issues, I am using chrome and I was able to browse through the chat link you send without any issue. Also can you give a sample link for 417-expectation failed?

**Comment by venkat7be1** [comment] 2015-05-16 22:20
http://slickdeals.net/forums/newreply.php?v=1&do=postreply&t=7862265
Here is the link. Error occurred when i tried to reply to the post. 

Also This piece of code takes really long time to execute few requests making the browsing experience really slow. Can this be fine tuned? Thanks

while (!String.IsNullOrEmpty(tmpLine = clientStreamReader.ReadLine()))
                {
                    requestLines.Add(tmpLine);
                }

**Comment by titanium007** [comment] 2015-05-18 22:30
I am not an expert in this. However I hope my recent commit would fix the authentication issue. Regarding slow reading, I believe its more related to IO wait than code. I checked on the link for "417 - Expectation Failed error". Couldn't reproduce it.

**Comment by venkat7be1** [comment] 2015-05-18 22:48
Thanks for Providing the fix, For Slow Reading i tried to rewriting the logic however i ended up having more issues in POST, But works faster for GET. Here is the code i modified, sorry for my bad code.

                byte[] bytes = new byte[client.receivebuffersize];
                netstream.read(bytes, 0, (int)client.receivebuffersize);
                string returndata = encoding.ascii.getstring(bytes);
                requestlines = returndata.replace("\r", "").replace("\0", "").split('\n').tolist();
                requestlines = requestlines.Where(s => !string.IsNullOrWhiteSpace(s)).Distinct().ToList();

Regarding "417 - Expectation Failed error", i still could able to reproduce the error on all 3 browsers. None of the Post events including login are successful in this site(Slickdeals.net) with the proxy.

**Comment by venkat7be1** [comment] 2015-05-18 22:57
Also I noticed webReq.Headers.Add(header[0], header[1]); will throw out of range exception exception if the header length is 1, Probably this needs to be modified to if (header.Length > 1). Please ignore if this is not making any sense, Thanks

   default:
                            if (header.Length > 0)
                                webReq.Headers.Add(header[0], header[1]);
                            else
                                webReq.Headers.Add(header[0], "");

                            break;

**Comment by titanium007** [comment] 2015-05-18 23:12
Can you clone this project and perhaps create a branch and then commit your changes using github client. I could look at it and pull in your changes to the main branch. Thanks for your suggestions. But I don't have much time nowadays to contribute. This was a learning project for me. So perhaps you could also learn by researching. One good tool you can use would be fiddler proxy. Using fiddler you can compare the reasons for error by looking the response headers fiddler returns and then the headers this proxy returns (use chrome development tools on chrome browser). Just FYI.

**Comment by venkat7be1** [comment] 2015-05-18 23:20
I am still trying to understand the code, I will try to commit the changes if any after some testing. even i am using this project for learning purpose, 
Again Any issues i will continue to post here and if can spend some time to answer that will be great. Thanks for your time.

**Comment by venkat7be1** [comment] 2015-05-20 00:36
Hi, 
 The Authentication issue still exists, The authentication for the site which i was trying is NTLM authentication and the fix add the headers for basic Authentication. Also even after entering the credentials and authentication is successful, Authentication popup will be prompted again for another request. This happens for every request of the page. Any idea how this can be fixed?

**Comment by titanium007** [comment] 2015-05-20 02:04
I reverted my change since its breaking other requests. I am not sure.

NTLM authentication is possible on internet? I always thought its used only in intranet sites.

The Httpwebrequest class handles all the heavy lifting for authentication in background. The only case it cannot handle without user input is basic authentication. Since it would need a username and password.

**Comment by venkat7be1** [comment] 2015-05-20 02:29
I have noticed lots of sites with NTLM Authentication on internet. Are you planning to fix this any time soon? if not probably i will try to fix it when i get a chance. Is there any other requests this change is breaking?

**Comment by titanium007** [comment] 2015-05-20 03:25
You are always welcome to do fixes. I don't have time to contribute like I said earlier. Sorry.

**Comment by titanium007** [comment] 2015-06-29 15:19
I looked at this issue again. I tested a website that uses basic authentication. Worked fine without any issue.

In the website you gave if you can give me  a sample login I can test it. Otherwise I am going to close this issue.

**Closed** 2015-07-03 16:05 UTC
